#!/bin/sh   # -*-pd-*-
# Quick Start for ZXID
######################
# Sampo Kellomäki (sampo@iki.fi)
# $Id: Quick,v 1.9 2010-01-08 02:10:09 sampo Exp $

make dep ENA_GEN=1
time (PATH=/usr/bin:/bin:/apps/bin LD_LIBRARY_PATH=/apps/lib make all ENA_GEN=1)

time (PATH=/usr/bin:/bin:/apps/bin LD_LIBRARY_PATH=/apps/lib make all ENA_GEN=1 ENA_PG=1)
time (LD_LIBRARY_PATH=/apps/lib make all ENA_GEN=1 ENA_PG=1)

# configure your web server to recognize zxid a CGI, e.g.
mini_httpd -p 8443 -c 'zxid*' -S -E zxid.pem -l /tmp/mini.stderr &
mini_httpd -p 8444 -c 'zxid*' -S -E /var/zxid/pem/enc-nopw-cert.pem -l /tmp/mini.stderr &
mini_httpd_zxid -zx 'PATH=/var/zxid/&WSP_PAT=**.wsp&SSO_PAT=**&DEBUG=0x7f' -p 8443 -c 'zxid*' -S -E /var/zxid/pem/enc-nopw-cert.pem
./zxid_httpd -zx 'PATH=/var/zxid/&WSP_PAT=*.wsp&SSO_PAT=*&DEBUG=8' -p 8443 -c 'zxid*' -S /var/zxid/pem/enc-nopw-cert.pem
curl -k https://sp.tas3.pt:8443/zxidenv.cgi
https://sp.tas3.pt:8443/zxidenv.cgi
https://sp.tas3.pt:8443/zxidenv.wsp

./zxcot -e http://idp.tas3.pt:8081/zxididp?o=S 'TAS3 Default Discovery Service (ID-WSF 2.0)' http://idp.tas3.pt:8081/zxididp?o=B urn:liberty:disco:2006-08 | ./zxcot -bs /var/zxid/idp.tas3.pt_8081/dimd/

./zxcot -e https://sp.tas3.pt:8443/zxidenv.wsp 'WSP test' https://sp.tas3.pt:8443/saml?o=B urn:zxidenv | ./zxcot -b /var/zxid/idp.tas3.pt_8081/dimd/

./zxcot -s /var/zxid/idp.tas3.pt_8081/cot/

./zxcall -c 'CPATH=/var/zxid/&URL=https://sp.tas3.pt:8443/saml' -a http://idp.tas3.pt:8081/zxididp?o=B test:foo -t urn:zxidenv -e '<req/>'

curl -v -k https://sp.tas3.pt:8443/zxidenv.wsp --data-binary '<req>Hello</req>'

echo Edit your /etc/hosts to contain
echo 127.0.0.1 localhost sp1.zxidcommon.org sp1.zxidsp.org idp1.zxidp.org sp.tas3.pt idp.tas3.pt
echo
echo Point your browser to
echo  http://sp1.zxidsp.org:8081/zxidhlo?o=E
echo  https://sp1.zxidsp.org:8443/zxidhlo?o=E
echo  https://sp1.zxidsp.org:8443/zxidhlo.pl?o=E      # Perl version
echo  https://sp1.zxidsp.org:8443/zxidhlo.php?o=E     # PHP version
echo  https://sp1.zxidsp.org:8443/zxidhrxmlwsc?o=E
echo  https://idp1.zxidp.org:8443/zxididp?o=F         # Local IdP
echo
echo  http://sp.tas3.pt:8080/zxidservlet/appdemo      # Main TAS3 demo
echo  http://sp.tas3.pt:8082/zxidhlo.pl?o=E
echo  http://sp.tas3.pt:8082/zxidhlo.php?o=E
echo  http://sp.tas3.pt:8082/protected/saml?o=E       # mod_auth_saml
echo  http://sp.tas3.pt:8082/protected/env.cgi
echo  http://sp.tas3.pt:8082/OS-Iconic
echo  http://idp.tas3.pt:8081/zxididp?o=F
echo
echo tail -f /var/tmp/zxid.stderr &
echo tail -f /var/zxid/log/act &
echo
echo wireshark -i lo -f 'port 8080 or port 8081'&
echo wireshark -i eth0 -f 'host 87.106.206.244' -k -S -l

(ip.addr eq 1.1.1.1)

STD TEST SETUP
--------------

export LD_LIBRARY_PATH=/apps/lib
ulimit -c unlimited
mini_httpd -p 8081 -c 'zxid*' &   # IdP
mini_httpd -p 8082 -c 'zxid*' &   # SP
./zxid_httpd -p 8081 -c 'zxid*' & # IdP
./zxid_httpd -p 8082 -c 'zxid*' & # SP
tailf /var/tmp/zxid.stderr &
tailf /var/zxid/log/xml.dbg | ~/zxid/xml-pretty.pl &
tailf /var/log/apache2/error.log | perl -pe 's/((zxidp)|(eid))/\e[1;31m$1\e[0m/g; s/, referer: .*?$//' &
tail -f tmp/err-httpd &
tailf ~/error.log | perl -pe 'substr($_,0,60)=""; s/((zxidp)|(eid))/\e[1;31m$1\e[0m/g; s/, referer: .*?$//' &

http://idp.tas3.pt:8081/zxididp?o=B
http://idp.tas3.pt:8081/zxididp?o=F
http://sp.tas3.pt:8082/zxidhlo?o=E

Testing
-------

http://idp.tas3.pt:8081/zxidtest.pl
./zxtest.pl -a -a -dx

emacs /apps/apache/std/conf/httpd.conf
/apps/apache/std/bin/apachectl start                  # Apache2
tailf tmp/err-httpd &

Testing Java
------------

make javazxid
export LD_LIBRARY_PATH=/home/sampo/zxid/zxidjava:/apps/lib:$LD_LIBRARY_PATH
export JAVA_HOME=/apps/java/j2sdk1.4.2
cd /home/sampo/apache-tomcat-5.5.20/
tail -f logs/catalina.out &
ulimit -c unlimited
killall java; bin/startup.sh
http://sp1.zxidsp.org:8080/zxidservlet/zxidHLO?o=E
http://sp.tas3.pt:8080/zxidservlet/appdemo

gdb /apps/java/j2sdk1.4.2/bin/java core
gdb /apps/java/j2sdk1.4.2/bin/java /d/sampo/apache-tomcat-5.5.20/core
tcpdump -lnA -s 1024 dst port 8080

./zxcall -d -a http://idp.tas3.pt:8081/zxididp?o=B tastest:tastest -t urn:x-foobar -e '<foobar>Do It!</foobar>'

GDB setup
---------

set env CONTENT_LENGTH=222
set env QUERY_STRING=o=S
set env LD_LIBRARY_PATH=/apps/lib
dir /aino/openssl-0.9.8q/ssl
dir /aino/openssl-0.9.8q/crypto/evp
dir /aino/openssl-0.9.8q/crypto/asn1
dir /aino/openssl-0.9.8q/crypto/pem
dir /aino/openssl-0.9.8q/crypto/x509
dir /aino/openssl-0.9.8q/crypto/object

dir /aino/openssl-1.0.0c/ssl
dir /aino/openssl-1.0.0c/crypto/evp
dir /aino/openssl-1.0.0c/crypto/asn1
dir /aino/openssl-1.0.0c/crypto/pem
dir /aino/openssl-1.0.0c/crypto/x509
dir /aino/openssl-1.0.0c/crypto/object

<<EOF: >>
