/* c/zx-is-aux.c - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
/* Code generation design Copyright (c) 2006 Sampo Kellomaki (sampo@iki.fi),
 * All Rights Reserved. NO WARRANTY. See file COPYING for terms and conditions
 * of use. Some aspects of code generation were driven by schema
 * descriptions that were used as input and may be subject to their own copyright.
 * Code generation uses a template, whose copyright statement follows. */

/** aux-templ.c  -  Auxiliary functions template: cloning, freeing, walking data
 ** Copyright (c) 2010 Sampo Kellomaki (sampo@iki.fi), All Rights Reserved.
 ** Copyright (c) 2006 Symlabs (symlabs@symlabs.com), All Rights Reserved.
 ** Author: Sampo Kellomaki (sampo@iki.fi)
 ** This is confidential unpublished proprietary source code of the author.
 ** NO WARRANTY, not even implied warranties. Contains trade secrets.
 ** Distribution prohibited unless authorized in writing.
 ** Licensed under Apache License 2.0, see file COPYING.
 ** Id: aux-templ.c,v 1.12 2008-10-04 23:42:14 sampo Exp $
 **
 ** 30.5.2006, created, Sampo Kellomaki (sampo@iki.fi)
 ** 6.8.2006, factored from enc-templ.c to separate file --Sampo
 **
 ** N.B: wo=wire order (needed for exc-c14n), so=schema order
 **/

#include <memory.h>
#include "errmac.h"
#include "zx.h"
#include "c/zx-const.h"
#include "c/zx-data.h"
#include "c/zx-is-data.h"



#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   is_Confirm
#define EL_STRUCT zx_is_Confirm_s
#define EL_NS     is
#define EL_TAG    Confirm

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_is_Confirm) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_is_Confirm(struct zx_ctx* c, struct zx_is_Confirm_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->name);

  for (se = &x->Help->gg;
       se && se->g.tok == zx_is_Help_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Help(c, (struct zx_is_Help_s*)se);
  zx_dup_strs_simple_elems(c, x->Hint);
  zx_dup_strs_simple_elems(c, x->Label);
  zx_dup_strs_simple_elems(c, x->Value);

}

/* FUNC(zx_DEEP_CLONE_is_Confirm) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_is_Confirm_s* zx_DEEP_CLONE_is_Confirm(struct zx_ctx* c, struct zx_is_Confirm_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_is_Confirm_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_is_Confirm_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->name = zx_clone_attr(c, x->name);

  for (enn = 0, e = &x->Help->gg;
       e && e->g.tok == zx_is_Help_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Help(c,(struct zx_is_Help_s*)e,dup_strs);
  	  if (!enn)
  	      x->Help = (struct zx_is_Help_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  x->Hint = zx_deep_clone_simple_elems(c,x->Hint, dup_strs);
  x->Label = zx_deep_clone_simple_elems(c,x->Label, dup_strs);
  x->Value = zx_deep_clone_simple_elems(c,x->Value, dup_strs);

  return x;
}

/* FUNC(zx_WALK_SO_is_Confirm) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_is_Confirm(struct zx_ctx* c, struct zx_is_Confirm_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Help->gg;
       e && e->g.tok == zx_is_Help_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Help(c, (struct zx_is_Help_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  ret = zx_walk_so_simple_elems(c, x->Hint, ctx, callback);
  if (ret)
    return ret;
  ret = zx_walk_so_simple_elems(c, x->Label, ctx, callback);
  if (ret)
    return ret;
  ret = zx_walk_so_simple_elems(c, x->Value, ctx, callback);
  if (ret)
    return ret;

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_is_Confirm) */

int zx_WALK_WO_is_Confirm(struct zx_ctx* c, struct zx_is_Confirm_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   is_Help
#define EL_STRUCT zx_is_Help_s
#define EL_NS     is
#define EL_TAG    Help

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_is_Help) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_is_Help(struct zx_ctx* c, struct zx_is_Help_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->label);
  zx_dup_attr(c, x->link);
  zx_dup_attr(c, x->moreLink);


}

/* FUNC(zx_DEEP_CLONE_is_Help) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_is_Help_s* zx_DEEP_CLONE_is_Help(struct zx_ctx* c, struct zx_is_Help_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_is_Help_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_is_Help_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->label = zx_clone_attr(c, x->label);
  x->link = zx_clone_attr(c, x->link);
  x->moreLink = zx_clone_attr(c, x->moreLink);


  return x;
}

/* FUNC(zx_WALK_SO_is_Help) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_is_Help(struct zx_ctx* c, struct zx_is_Help_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;


  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_is_Help) */

int zx_WALK_WO_is_Help(struct zx_ctx* c, struct zx_is_Help_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   is_Inquiry
#define EL_STRUCT zx_is_Inquiry_s
#define EL_NS     is
#define EL_TAG    Inquiry

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_is_Inquiry) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_is_Inquiry(struct zx_ctx* c, struct zx_is_Inquiry_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->id);
  zx_dup_attr(c, x->title);

  for (se = &x->Help->gg;
       se && se->g.tok == zx_is_Help_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Help(c, (struct zx_is_Help_s*)se);
  for (se = &x->Select->gg;
       se && se->g.tok == zx_is_Select_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Select(c, (struct zx_is_Select_s*)se);
  for (se = &x->Confirm->gg;
       se && se->g.tok == zx_is_Confirm_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Confirm(c, (struct zx_is_Confirm_s*)se);
  for (se = &x->Text->gg;
       se && se->g.tok == zx_is_Text_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Text(c, (struct zx_is_Text_s*)se);

}

/* FUNC(zx_DEEP_CLONE_is_Inquiry) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_is_Inquiry_s* zx_DEEP_CLONE_is_Inquiry(struct zx_ctx* c, struct zx_is_Inquiry_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_is_Inquiry_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_is_Inquiry_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->id = zx_clone_attr(c, x->id);
  x->title = zx_clone_attr(c, x->title);

  for (enn = 0, e = &x->Help->gg;
       e && e->g.tok == zx_is_Help_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Help(c,(struct zx_is_Help_s*)e,dup_strs);
  	  if (!enn)
  	      x->Help = (struct zx_is_Help_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Select->gg;
       e && e->g.tok == zx_is_Select_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Select(c,(struct zx_is_Select_s*)e,dup_strs);
  	  if (!enn)
  	      x->Select = (struct zx_is_Select_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Confirm->gg;
       e && e->g.tok == zx_is_Confirm_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Confirm(c,(struct zx_is_Confirm_s*)e,dup_strs);
  	  if (!enn)
  	      x->Confirm = (struct zx_is_Confirm_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Text->gg;
       e && e->g.tok == zx_is_Text_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Text(c,(struct zx_is_Text_s*)e,dup_strs);
  	  if (!enn)
  	      x->Text = (struct zx_is_Text_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_is_Inquiry) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_is_Inquiry(struct zx_ctx* c, struct zx_is_Inquiry_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Help->gg;
       e && e->g.tok == zx_is_Help_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Help(c, (struct zx_is_Help_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Select->gg;
       e && e->g.tok == zx_is_Select_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Select(c, (struct zx_is_Select_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Confirm->gg;
       e && e->g.tok == zx_is_Confirm_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Confirm(c, (struct zx_is_Confirm_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Text->gg;
       e && e->g.tok == zx_is_Text_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Text(c, (struct zx_is_Text_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_is_Inquiry) */

int zx_WALK_WO_is_Inquiry(struct zx_ctx* c, struct zx_is_Inquiry_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   is_InteractionRequest
#define EL_STRUCT zx_is_InteractionRequest_s
#define EL_NS     is
#define EL_TAG    InteractionRequest

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_is_InteractionRequest) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_is_InteractionRequest(struct zx_ctx* c, struct zx_is_InteractionRequest_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->id);
  zx_dup_attr(c, x->language);
  zx_dup_attr(c, x->maxInteractTime);
  zx_dup_attr(c, x->signed_is_c_keyword);

  for (se = &x->Inquiry->gg;
       se && se->g.tok == zx_is_Inquiry_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Inquiry(c, (struct zx_is_Inquiry_s*)se);
  for (se = &x->KeyInfo->gg;
       se && se->g.tok == zx_ds_KeyInfo_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_KeyInfo(c, (struct zx_ds_KeyInfo_s*)se);

}

/* FUNC(zx_DEEP_CLONE_is_InteractionRequest) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_is_InteractionRequest_s* zx_DEEP_CLONE_is_InteractionRequest(struct zx_ctx* c, struct zx_is_InteractionRequest_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_is_InteractionRequest_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_is_InteractionRequest_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->id = zx_clone_attr(c, x->id);
  x->language = zx_clone_attr(c, x->language);
  x->maxInteractTime = zx_clone_attr(c, x->maxInteractTime);
  x->signed_is_c_keyword = zx_clone_attr(c, x->signed_is_c_keyword);

  for (enn = 0, e = &x->Inquiry->gg;
       e && e->g.tok == zx_is_Inquiry_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Inquiry(c,(struct zx_is_Inquiry_s*)e,dup_strs);
  	  if (!enn)
  	      x->Inquiry = (struct zx_is_Inquiry_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->KeyInfo->gg;
       e && e->g.tok == zx_ds_KeyInfo_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_KeyInfo(c,(struct zx_ds_KeyInfo_s*)e,dup_strs);
  	  if (!enn)
  	      x->KeyInfo = (struct zx_ds_KeyInfo_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_is_InteractionRequest) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_is_InteractionRequest(struct zx_ctx* c, struct zx_is_InteractionRequest_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Inquiry->gg;
       e && e->g.tok == zx_is_Inquiry_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Inquiry(c, (struct zx_is_Inquiry_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->KeyInfo->gg;
       e && e->g.tok == zx_ds_KeyInfo_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_KeyInfo(c, (struct zx_ds_KeyInfo_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_is_InteractionRequest) */

int zx_WALK_WO_is_InteractionRequest(struct zx_ctx* c, struct zx_is_InteractionRequest_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   is_InteractionResponse
#define EL_STRUCT zx_is_InteractionResponse_s
#define EL_NS     is
#define EL_TAG    InteractionResponse

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_is_InteractionResponse) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_is_InteractionResponse(struct zx_ctx* c, struct zx_is_InteractionResponse_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */


  for (se = &x->Status->gg;
       se && se->g.tok == zx_lu_Status_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_lu_Status(c, (struct zx_lu_Status_s*)se);
  for (se = &x->InteractionStatement->gg;
       se && se->g.tok == zx_is_InteractionStatement_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_InteractionStatement(c, (struct zx_is_InteractionStatement_s*)se);
  for (se = &x->Parameter->gg;
       se && se->g.tok == zx_is_Parameter_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Parameter(c, (struct zx_is_Parameter_s*)se);

}

/* FUNC(zx_DEEP_CLONE_is_InteractionResponse) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_is_InteractionResponse_s* zx_DEEP_CLONE_is_InteractionResponse(struct zx_ctx* c, struct zx_is_InteractionResponse_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_is_InteractionResponse_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_is_InteractionResponse_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */


  for (enn = 0, e = &x->Status->gg;
       e && e->g.tok == zx_lu_Status_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_lu_Status(c,(struct zx_lu_Status_s*)e,dup_strs);
  	  if (!enn)
  	      x->Status = (struct zx_lu_Status_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->InteractionStatement->gg;
       e && e->g.tok == zx_is_InteractionStatement_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_InteractionStatement(c,(struct zx_is_InteractionStatement_s*)e,dup_strs);
  	  if (!enn)
  	      x->InteractionStatement = (struct zx_is_InteractionStatement_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Parameter->gg;
       e && e->g.tok == zx_is_Parameter_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Parameter(c,(struct zx_is_Parameter_s*)e,dup_strs);
  	  if (!enn)
  	      x->Parameter = (struct zx_is_Parameter_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_is_InteractionResponse) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_is_InteractionResponse(struct zx_ctx* c, struct zx_is_InteractionResponse_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Status->gg;
       e && e->g.tok == zx_lu_Status_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_lu_Status(c, (struct zx_lu_Status_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->InteractionStatement->gg;
       e && e->g.tok == zx_is_InteractionStatement_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_InteractionStatement(c, (struct zx_is_InteractionStatement_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Parameter->gg;
       e && e->g.tok == zx_is_Parameter_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Parameter(c, (struct zx_is_Parameter_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_is_InteractionResponse) */

int zx_WALK_WO_is_InteractionResponse(struct zx_ctx* c, struct zx_is_InteractionResponse_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   is_InteractionStatement
#define EL_STRUCT zx_is_InteractionStatement_s
#define EL_NS     is
#define EL_TAG    InteractionStatement

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_is_InteractionStatement) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_is_InteractionStatement(struct zx_ctx* c, struct zx_is_InteractionStatement_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */


  for (se = &x->Inquiry->gg;
       se && se->g.tok == zx_is_Inquiry_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Inquiry(c, (struct zx_is_Inquiry_s*)se);
  for (se = &x->Signature->gg;
       se && se->g.tok == zx_ds_Signature_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_Signature(c, (struct zx_ds_Signature_s*)se);

}

/* FUNC(zx_DEEP_CLONE_is_InteractionStatement) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_is_InteractionStatement_s* zx_DEEP_CLONE_is_InteractionStatement(struct zx_ctx* c, struct zx_is_InteractionStatement_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_is_InteractionStatement_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_is_InteractionStatement_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */


  for (enn = 0, e = &x->Inquiry->gg;
       e && e->g.tok == zx_is_Inquiry_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Inquiry(c,(struct zx_is_Inquiry_s*)e,dup_strs);
  	  if (!enn)
  	      x->Inquiry = (struct zx_is_Inquiry_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Signature->gg;
       e && e->g.tok == zx_ds_Signature_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_Signature(c,(struct zx_ds_Signature_s*)e,dup_strs);
  	  if (!enn)
  	      x->Signature = (struct zx_ds_Signature_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_is_InteractionStatement) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_is_InteractionStatement(struct zx_ctx* c, struct zx_is_InteractionStatement_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Inquiry->gg;
       e && e->g.tok == zx_is_Inquiry_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Inquiry(c, (struct zx_is_Inquiry_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Signature->gg;
       e && e->g.tok == zx_ds_Signature_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_Signature(c, (struct zx_ds_Signature_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_is_InteractionStatement) */

int zx_WALK_WO_is_InteractionStatement(struct zx_ctx* c, struct zx_is_InteractionStatement_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   is_Item
#define EL_STRUCT zx_is_Item_s
#define EL_NS     is
#define EL_TAG    Item

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_is_Item) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_is_Item(struct zx_ctx* c, struct zx_is_Item_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->label);
  zx_dup_attr(c, x->value);

  zx_dup_strs_simple_elems(c, x->Hint);

}

/* FUNC(zx_DEEP_CLONE_is_Item) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_is_Item_s* zx_DEEP_CLONE_is_Item(struct zx_ctx* c, struct zx_is_Item_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_is_Item_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_is_Item_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->label = zx_clone_attr(c, x->label);
  x->value = zx_clone_attr(c, x->value);

  x->Hint = zx_deep_clone_simple_elems(c,x->Hint, dup_strs);

  return x;
}

/* FUNC(zx_WALK_SO_is_Item) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_is_Item(struct zx_ctx* c, struct zx_is_Item_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  ret = zx_walk_so_simple_elems(c, x->Hint, ctx, callback);
  if (ret)
    return ret;

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_is_Item) */

int zx_WALK_WO_is_Item(struct zx_ctx* c, struct zx_is_Item_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   is_Parameter
#define EL_STRUCT zx_is_Parameter_s
#define EL_NS     is
#define EL_TAG    Parameter

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_is_Parameter) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_is_Parameter(struct zx_ctx* c, struct zx_is_Parameter_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->name);
  zx_dup_attr(c, x->value);


}

/* FUNC(zx_DEEP_CLONE_is_Parameter) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_is_Parameter_s* zx_DEEP_CLONE_is_Parameter(struct zx_ctx* c, struct zx_is_Parameter_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_is_Parameter_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_is_Parameter_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->name = zx_clone_attr(c, x->name);
  x->value = zx_clone_attr(c, x->value);


  return x;
}

/* FUNC(zx_WALK_SO_is_Parameter) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_is_Parameter(struct zx_ctx* c, struct zx_is_Parameter_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;


  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_is_Parameter) */

int zx_WALK_WO_is_Parameter(struct zx_ctx* c, struct zx_is_Parameter_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   is_Select
#define EL_STRUCT zx_is_Select_s
#define EL_NS     is
#define EL_TAG    Select

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_is_Select) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_is_Select(struct zx_ctx* c, struct zx_is_Select_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->multiple);
  zx_dup_attr(c, x->name);

  for (se = &x->Help->gg;
       se && se->g.tok == zx_is_Help_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Help(c, (struct zx_is_Help_s*)se);
  zx_dup_strs_simple_elems(c, x->Hint);
  zx_dup_strs_simple_elems(c, x->Label);
  zx_dup_strs_simple_elems(c, x->Value);
  for (se = &x->Item->gg;
       se && se->g.tok == zx_is_Item_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Item(c, (struct zx_is_Item_s*)se);

}

/* FUNC(zx_DEEP_CLONE_is_Select) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_is_Select_s* zx_DEEP_CLONE_is_Select(struct zx_ctx* c, struct zx_is_Select_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_is_Select_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_is_Select_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->multiple = zx_clone_attr(c, x->multiple);
  x->name = zx_clone_attr(c, x->name);

  for (enn = 0, e = &x->Help->gg;
       e && e->g.tok == zx_is_Help_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Help(c,(struct zx_is_Help_s*)e,dup_strs);
  	  if (!enn)
  	      x->Help = (struct zx_is_Help_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  x->Hint = zx_deep_clone_simple_elems(c,x->Hint, dup_strs);
  x->Label = zx_deep_clone_simple_elems(c,x->Label, dup_strs);
  x->Value = zx_deep_clone_simple_elems(c,x->Value, dup_strs);
  for (enn = 0, e = &x->Item->gg;
       e && e->g.tok == zx_is_Item_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Item(c,(struct zx_is_Item_s*)e,dup_strs);
  	  if (!enn)
  	      x->Item = (struct zx_is_Item_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_is_Select) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_is_Select(struct zx_ctx* c, struct zx_is_Select_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Help->gg;
       e && e->g.tok == zx_is_Help_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Help(c, (struct zx_is_Help_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  ret = zx_walk_so_simple_elems(c, x->Hint, ctx, callback);
  if (ret)
    return ret;
  ret = zx_walk_so_simple_elems(c, x->Label, ctx, callback);
  if (ret)
    return ret;
  ret = zx_walk_so_simple_elems(c, x->Value, ctx, callback);
  if (ret)
    return ret;
  for (e = &x->Item->gg;
       e && e->g.tok == zx_is_Item_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Item(c, (struct zx_is_Item_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_is_Select) */

int zx_WALK_WO_is_Select(struct zx_ctx* c, struct zx_is_Select_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   is_Text
#define EL_STRUCT zx_is_Text_s
#define EL_NS     is
#define EL_TAG    Text

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_is_Text) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_is_Text(struct zx_ctx* c, struct zx_is_Text_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->format);
  zx_dup_attr(c, x->maxChars);
  zx_dup_attr(c, x->minChars);
  zx_dup_attr(c, x->name);

  for (se = &x->Help->gg;
       se && se->g.tok == zx_is_Help_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_is_Help(c, (struct zx_is_Help_s*)se);
  zx_dup_strs_simple_elems(c, x->Hint);
  zx_dup_strs_simple_elems(c, x->Label);
  zx_dup_strs_simple_elems(c, x->Value);

}

/* FUNC(zx_DEEP_CLONE_is_Text) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_is_Text_s* zx_DEEP_CLONE_is_Text(struct zx_ctx* c, struct zx_is_Text_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_is_Text_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_is_Text_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->format = zx_clone_attr(c, x->format);
  x->maxChars = zx_clone_attr(c, x->maxChars);
  x->minChars = zx_clone_attr(c, x->minChars);
  x->name = zx_clone_attr(c, x->name);

  for (enn = 0, e = &x->Help->gg;
       e && e->g.tok == zx_is_Help_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_is_Help(c,(struct zx_is_Help_s*)e,dup_strs);
  	  if (!enn)
  	      x->Help = (struct zx_is_Help_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  x->Hint = zx_deep_clone_simple_elems(c,x->Hint, dup_strs);
  x->Label = zx_deep_clone_simple_elems(c,x->Label, dup_strs);
  x->Value = zx_deep_clone_simple_elems(c,x->Value, dup_strs);

  return x;
}

/* FUNC(zx_WALK_SO_is_Text) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_is_Text(struct zx_ctx* c, struct zx_is_Text_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Help->gg;
       e && e->g.tok == zx_is_Help_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_is_Help(c, (struct zx_is_Help_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  ret = zx_walk_so_simple_elems(c, x->Hint, ctx, callback);
  if (ret)
    return ret;
  ret = zx_walk_so_simple_elems(c, x->Label, ctx, callback);
  if (ret)
    return ret;
  ret = zx_walk_so_simple_elems(c, x->Value, ctx, callback);
  if (ret)
    return ret;

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_is_Text) */

int zx_WALK_WO_is_Text(struct zx_ctx* c, struct zx_is_Text_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif


/* EOF -- c/zx-is-aux.c */
