/* c/zx-xenc-aux.c - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
/* Code generation design Copyright (c) 2006 Sampo Kellomaki (sampo@iki.fi),
 * All Rights Reserved. NO WARRANTY. See file COPYING for terms and conditions
 * of use. Some aspects of code generation were driven by schema
 * descriptions that were used as input and may be subject to their own copyright.
 * Code generation uses a template, whose copyright statement follows. */

/** aux-templ.c  -  Auxiliary functions template: cloning, freeing, walking data
 ** Copyright (c) 2010 Sampo Kellomaki (sampo@iki.fi), All Rights Reserved.
 ** Copyright (c) 2006 Symlabs (symlabs@symlabs.com), All Rights Reserved.
 ** Author: Sampo Kellomaki (sampo@iki.fi)
 ** This is confidential unpublished proprietary source code of the author.
 ** NO WARRANTY, not even implied warranties. Contains trade secrets.
 ** Distribution prohibited unless authorized in writing.
 ** Licensed under Apache License 2.0, see file COPYING.
 ** Id: aux-templ.c,v 1.12 2008-10-04 23:42:14 sampo Exp $
 **
 ** 30.5.2006, created, Sampo Kellomaki (sampo@iki.fi)
 ** 6.8.2006, factored from enc-templ.c to separate file --Sampo
 **
 ** N.B: wo=wire order (needed for exc-c14n), so=schema order
 **/

#include <memory.h>
#include "errmac.h"
#include "zx.h"
#include "c/zx-const.h"
#include "c/zx-data.h"
#include "c/zx-xenc-data.h"



#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_AgreementMethod
#define EL_STRUCT zx_xenc_AgreementMethod_s
#define EL_NS     xenc
#define EL_TAG    AgreementMethod

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_AgreementMethod) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_AgreementMethod(struct zx_ctx* c, struct zx_xenc_AgreementMethod_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->Algorithm);

  zx_dup_strs_simple_elems(c, x->KA_Nonce);
  for (se = &x->OriginatorKeyInfo->gg;
       se && se->g.tok == zx_xenc_OriginatorKeyInfo_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_OriginatorKeyInfo(c, (struct zx_xenc_OriginatorKeyInfo_s*)se);
  for (se = &x->RecipientKeyInfo->gg;
       se && se->g.tok == zx_xenc_RecipientKeyInfo_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_RecipientKeyInfo(c, (struct zx_xenc_RecipientKeyInfo_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xenc_AgreementMethod) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_AgreementMethod_s* zx_DEEP_CLONE_xenc_AgreementMethod(struct zx_ctx* c, struct zx_xenc_AgreementMethod_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_AgreementMethod_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_AgreementMethod_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->Algorithm = zx_clone_attr(c, x->Algorithm);

  x->KA_Nonce = zx_deep_clone_simple_elems(c,x->KA_Nonce, dup_strs);
  for (enn = 0, e = &x->OriginatorKeyInfo->gg;
       e && e->g.tok == zx_xenc_OriginatorKeyInfo_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_OriginatorKeyInfo(c,(struct zx_xenc_OriginatorKeyInfo_s*)e,dup_strs);
  	  if (!enn)
  	      x->OriginatorKeyInfo = (struct zx_xenc_OriginatorKeyInfo_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->RecipientKeyInfo->gg;
       e && e->g.tok == zx_xenc_RecipientKeyInfo_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_RecipientKeyInfo(c,(struct zx_xenc_RecipientKeyInfo_s*)e,dup_strs);
  	  if (!enn)
  	      x->RecipientKeyInfo = (struct zx_xenc_RecipientKeyInfo_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xenc_AgreementMethod) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_AgreementMethod(struct zx_ctx* c, struct zx_xenc_AgreementMethod_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  ret = zx_walk_so_simple_elems(c, x->KA_Nonce, ctx, callback);
  if (ret)
    return ret;
  for (e = &x->OriginatorKeyInfo->gg;
       e && e->g.tok == zx_xenc_OriginatorKeyInfo_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_OriginatorKeyInfo(c, (struct zx_xenc_OriginatorKeyInfo_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->RecipientKeyInfo->gg;
       e && e->g.tok == zx_xenc_RecipientKeyInfo_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_RecipientKeyInfo(c, (struct zx_xenc_RecipientKeyInfo_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_AgreementMethod) */

int zx_WALK_WO_xenc_AgreementMethod(struct zx_ctx* c, struct zx_xenc_AgreementMethod_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_CipherData
#define EL_STRUCT zx_xenc_CipherData_s
#define EL_NS     xenc
#define EL_TAG    CipherData

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_CipherData) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_CipherData(struct zx_ctx* c, struct zx_xenc_CipherData_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */


  zx_dup_strs_simple_elems(c, x->CipherValue);
  for (se = &x->CipherReference->gg;
       se && se->g.tok == zx_xenc_CipherReference_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_CipherReference(c, (struct zx_xenc_CipherReference_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xenc_CipherData) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_CipherData_s* zx_DEEP_CLONE_xenc_CipherData(struct zx_ctx* c, struct zx_xenc_CipherData_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_CipherData_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_CipherData_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */


  x->CipherValue = zx_deep_clone_simple_elems(c,x->CipherValue, dup_strs);
  for (enn = 0, e = &x->CipherReference->gg;
       e && e->g.tok == zx_xenc_CipherReference_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_CipherReference(c,(struct zx_xenc_CipherReference_s*)e,dup_strs);
  	  if (!enn)
  	      x->CipherReference = (struct zx_xenc_CipherReference_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xenc_CipherData) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_CipherData(struct zx_ctx* c, struct zx_xenc_CipherData_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  ret = zx_walk_so_simple_elems(c, x->CipherValue, ctx, callback);
  if (ret)
    return ret;
  for (e = &x->CipherReference->gg;
       e && e->g.tok == zx_xenc_CipherReference_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_CipherReference(c, (struct zx_xenc_CipherReference_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_CipherData) */

int zx_WALK_WO_xenc_CipherData(struct zx_ctx* c, struct zx_xenc_CipherData_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_CipherReference
#define EL_STRUCT zx_xenc_CipherReference_s
#define EL_NS     xenc
#define EL_TAG    CipherReference

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_CipherReference) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_CipherReference(struct zx_ctx* c, struct zx_xenc_CipherReference_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->URI);

  for (se = &x->Transforms->gg;
       se && se->g.tok == zx_xenc_Transforms_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_Transforms(c, (struct zx_xenc_Transforms_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xenc_CipherReference) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_CipherReference_s* zx_DEEP_CLONE_xenc_CipherReference(struct zx_ctx* c, struct zx_xenc_CipherReference_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_CipherReference_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_CipherReference_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->URI = zx_clone_attr(c, x->URI);

  for (enn = 0, e = &x->Transforms->gg;
       e && e->g.tok == zx_xenc_Transforms_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_Transforms(c,(struct zx_xenc_Transforms_s*)e,dup_strs);
  	  if (!enn)
  	      x->Transforms = (struct zx_xenc_Transforms_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xenc_CipherReference) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_CipherReference(struct zx_ctx* c, struct zx_xenc_CipherReference_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Transforms->gg;
       e && e->g.tok == zx_xenc_Transforms_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_Transforms(c, (struct zx_xenc_Transforms_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_CipherReference) */

int zx_WALK_WO_xenc_CipherReference(struct zx_ctx* c, struct zx_xenc_CipherReference_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_DataReference
#define EL_STRUCT zx_xenc_DataReference_s
#define EL_NS     xenc
#define EL_TAG    DataReference

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_DataReference) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_DataReference(struct zx_ctx* c, struct zx_xenc_DataReference_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->URI);


}

/* FUNC(zx_DEEP_CLONE_xenc_DataReference) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_DataReference_s* zx_DEEP_CLONE_xenc_DataReference(struct zx_ctx* c, struct zx_xenc_DataReference_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_DataReference_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_DataReference_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->URI = zx_clone_attr(c, x->URI);


  return x;
}

/* FUNC(zx_WALK_SO_xenc_DataReference) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_DataReference(struct zx_ctx* c, struct zx_xenc_DataReference_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;


  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_DataReference) */

int zx_WALK_WO_xenc_DataReference(struct zx_ctx* c, struct zx_xenc_DataReference_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_EncryptedData
#define EL_STRUCT zx_xenc_EncryptedData_s
#define EL_NS     xenc
#define EL_TAG    EncryptedData

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_EncryptedData) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_EncryptedData(struct zx_ctx* c, struct zx_xenc_EncryptedData_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->Encoding);
  zx_dup_attr(c, x->Id);
  zx_dup_attr(c, x->MimeType);
  zx_dup_attr(c, x->Type);

  for (se = &x->EncryptionMethod->gg;
       se && se->g.tok == zx_xenc_EncryptionMethod_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_EncryptionMethod(c, (struct zx_xenc_EncryptionMethod_s*)se);
  for (se = &x->KeyInfo->gg;
       se && se->g.tok == zx_ds_KeyInfo_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_KeyInfo(c, (struct zx_ds_KeyInfo_s*)se);
  for (se = &x->CipherData->gg;
       se && se->g.tok == zx_xenc_CipherData_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_CipherData(c, (struct zx_xenc_CipherData_s*)se);
  for (se = &x->EncryptionProperties->gg;
       se && se->g.tok == zx_xenc_EncryptionProperties_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_EncryptionProperties(c, (struct zx_xenc_EncryptionProperties_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xenc_EncryptedData) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_EncryptedData_s* zx_DEEP_CLONE_xenc_EncryptedData(struct zx_ctx* c, struct zx_xenc_EncryptedData_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_EncryptedData_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_EncryptedData_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->Encoding = zx_clone_attr(c, x->Encoding);
  x->Id = zx_clone_attr(c, x->Id);
  x->MimeType = zx_clone_attr(c, x->MimeType);
  x->Type = zx_clone_attr(c, x->Type);

  for (enn = 0, e = &x->EncryptionMethod->gg;
       e && e->g.tok == zx_xenc_EncryptionMethod_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_EncryptionMethod(c,(struct zx_xenc_EncryptionMethod_s*)e,dup_strs);
  	  if (!enn)
  	      x->EncryptionMethod = (struct zx_xenc_EncryptionMethod_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->KeyInfo->gg;
       e && e->g.tok == zx_ds_KeyInfo_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_KeyInfo(c,(struct zx_ds_KeyInfo_s*)e,dup_strs);
  	  if (!enn)
  	      x->KeyInfo = (struct zx_ds_KeyInfo_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->CipherData->gg;
       e && e->g.tok == zx_xenc_CipherData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_CipherData(c,(struct zx_xenc_CipherData_s*)e,dup_strs);
  	  if (!enn)
  	      x->CipherData = (struct zx_xenc_CipherData_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->EncryptionProperties->gg;
       e && e->g.tok == zx_xenc_EncryptionProperties_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_EncryptionProperties(c,(struct zx_xenc_EncryptionProperties_s*)e,dup_strs);
  	  if (!enn)
  	      x->EncryptionProperties = (struct zx_xenc_EncryptionProperties_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xenc_EncryptedData) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_EncryptedData(struct zx_ctx* c, struct zx_xenc_EncryptedData_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->EncryptionMethod->gg;
       e && e->g.tok == zx_xenc_EncryptionMethod_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_EncryptionMethod(c, (struct zx_xenc_EncryptionMethod_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->KeyInfo->gg;
       e && e->g.tok == zx_ds_KeyInfo_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_KeyInfo(c, (struct zx_ds_KeyInfo_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->CipherData->gg;
       e && e->g.tok == zx_xenc_CipherData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_CipherData(c, (struct zx_xenc_CipherData_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->EncryptionProperties->gg;
       e && e->g.tok == zx_xenc_EncryptionProperties_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_EncryptionProperties(c, (struct zx_xenc_EncryptionProperties_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_EncryptedData) */

int zx_WALK_WO_xenc_EncryptedData(struct zx_ctx* c, struct zx_xenc_EncryptedData_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_EncryptedKey
#define EL_STRUCT zx_xenc_EncryptedKey_s
#define EL_NS     xenc
#define EL_TAG    EncryptedKey

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_EncryptedKey) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_EncryptedKey(struct zx_ctx* c, struct zx_xenc_EncryptedKey_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->Encoding);
  zx_dup_attr(c, x->Id);
  zx_dup_attr(c, x->MimeType);
  zx_dup_attr(c, x->Recipient);
  zx_dup_attr(c, x->Type);

  for (se = &x->EncryptionMethod->gg;
       se && se->g.tok == zx_xenc_EncryptionMethod_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_EncryptionMethod(c, (struct zx_xenc_EncryptionMethod_s*)se);
  for (se = &x->KeyInfo->gg;
       se && se->g.tok == zx_ds_KeyInfo_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_KeyInfo(c, (struct zx_ds_KeyInfo_s*)se);
  for (se = &x->CipherData->gg;
       se && se->g.tok == zx_xenc_CipherData_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_CipherData(c, (struct zx_xenc_CipherData_s*)se);
  for (se = &x->EncryptionProperties->gg;
       se && se->g.tok == zx_xenc_EncryptionProperties_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_EncryptionProperties(c, (struct zx_xenc_EncryptionProperties_s*)se);
  for (se = &x->ReferenceList->gg;
       se && se->g.tok == zx_xenc_ReferenceList_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_ReferenceList(c, (struct zx_xenc_ReferenceList_s*)se);
  zx_dup_strs_simple_elems(c, x->CarriedKeyName);

}

/* FUNC(zx_DEEP_CLONE_xenc_EncryptedKey) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_EncryptedKey_s* zx_DEEP_CLONE_xenc_EncryptedKey(struct zx_ctx* c, struct zx_xenc_EncryptedKey_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_EncryptedKey_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_EncryptedKey_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->Encoding = zx_clone_attr(c, x->Encoding);
  x->Id = zx_clone_attr(c, x->Id);
  x->MimeType = zx_clone_attr(c, x->MimeType);
  x->Recipient = zx_clone_attr(c, x->Recipient);
  x->Type = zx_clone_attr(c, x->Type);

  for (enn = 0, e = &x->EncryptionMethod->gg;
       e && e->g.tok == zx_xenc_EncryptionMethod_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_EncryptionMethod(c,(struct zx_xenc_EncryptionMethod_s*)e,dup_strs);
  	  if (!enn)
  	      x->EncryptionMethod = (struct zx_xenc_EncryptionMethod_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->KeyInfo->gg;
       e && e->g.tok == zx_ds_KeyInfo_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_KeyInfo(c,(struct zx_ds_KeyInfo_s*)e,dup_strs);
  	  if (!enn)
  	      x->KeyInfo = (struct zx_ds_KeyInfo_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->CipherData->gg;
       e && e->g.tok == zx_xenc_CipherData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_CipherData(c,(struct zx_xenc_CipherData_s*)e,dup_strs);
  	  if (!enn)
  	      x->CipherData = (struct zx_xenc_CipherData_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->EncryptionProperties->gg;
       e && e->g.tok == zx_xenc_EncryptionProperties_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_EncryptionProperties(c,(struct zx_xenc_EncryptionProperties_s*)e,dup_strs);
  	  if (!enn)
  	      x->EncryptionProperties = (struct zx_xenc_EncryptionProperties_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->ReferenceList->gg;
       e && e->g.tok == zx_xenc_ReferenceList_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_ReferenceList(c,(struct zx_xenc_ReferenceList_s*)e,dup_strs);
  	  if (!enn)
  	      x->ReferenceList = (struct zx_xenc_ReferenceList_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  x->CarriedKeyName = zx_deep_clone_simple_elems(c,x->CarriedKeyName, dup_strs);

  return x;
}

/* FUNC(zx_WALK_SO_xenc_EncryptedKey) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_EncryptedKey(struct zx_ctx* c, struct zx_xenc_EncryptedKey_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->EncryptionMethod->gg;
       e && e->g.tok == zx_xenc_EncryptionMethod_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_EncryptionMethod(c, (struct zx_xenc_EncryptionMethod_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->KeyInfo->gg;
       e && e->g.tok == zx_ds_KeyInfo_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_KeyInfo(c, (struct zx_ds_KeyInfo_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->CipherData->gg;
       e && e->g.tok == zx_xenc_CipherData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_CipherData(c, (struct zx_xenc_CipherData_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->EncryptionProperties->gg;
       e && e->g.tok == zx_xenc_EncryptionProperties_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_EncryptionProperties(c, (struct zx_xenc_EncryptionProperties_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->ReferenceList->gg;
       e && e->g.tok == zx_xenc_ReferenceList_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_ReferenceList(c, (struct zx_xenc_ReferenceList_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  ret = zx_walk_so_simple_elems(c, x->CarriedKeyName, ctx, callback);
  if (ret)
    return ret;

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_EncryptedKey) */

int zx_WALK_WO_xenc_EncryptedKey(struct zx_ctx* c, struct zx_xenc_EncryptedKey_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_EncryptionMethod
#define EL_STRUCT zx_xenc_EncryptionMethod_s
#define EL_NS     xenc
#define EL_TAG    EncryptionMethod

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_EncryptionMethod) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_EncryptionMethod(struct zx_ctx* c, struct zx_xenc_EncryptionMethod_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->Algorithm);

  zx_dup_strs_simple_elems(c, x->KeySize);
  zx_dup_strs_simple_elems(c, x->OAEPparams);

}

/* FUNC(zx_DEEP_CLONE_xenc_EncryptionMethod) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_EncryptionMethod_s* zx_DEEP_CLONE_xenc_EncryptionMethod(struct zx_ctx* c, struct zx_xenc_EncryptionMethod_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_EncryptionMethod_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_EncryptionMethod_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->Algorithm = zx_clone_attr(c, x->Algorithm);

  x->KeySize = zx_deep_clone_simple_elems(c,x->KeySize, dup_strs);
  x->OAEPparams = zx_deep_clone_simple_elems(c,x->OAEPparams, dup_strs);

  return x;
}

/* FUNC(zx_WALK_SO_xenc_EncryptionMethod) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_EncryptionMethod(struct zx_ctx* c, struct zx_xenc_EncryptionMethod_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  ret = zx_walk_so_simple_elems(c, x->KeySize, ctx, callback);
  if (ret)
    return ret;
  ret = zx_walk_so_simple_elems(c, x->OAEPparams, ctx, callback);
  if (ret)
    return ret;

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_EncryptionMethod) */

int zx_WALK_WO_xenc_EncryptionMethod(struct zx_ctx* c, struct zx_xenc_EncryptionMethod_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_EncryptionProperties
#define EL_STRUCT zx_xenc_EncryptionProperties_s
#define EL_NS     xenc
#define EL_TAG    EncryptionProperties

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_EncryptionProperties) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_EncryptionProperties(struct zx_ctx* c, struct zx_xenc_EncryptionProperties_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->Id);

  for (se = &x->EncryptionProperty->gg;
       se && se->g.tok == zx_xenc_EncryptionProperty_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_EncryptionProperty(c, (struct zx_xenc_EncryptionProperty_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xenc_EncryptionProperties) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_EncryptionProperties_s* zx_DEEP_CLONE_xenc_EncryptionProperties(struct zx_ctx* c, struct zx_xenc_EncryptionProperties_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_EncryptionProperties_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_EncryptionProperties_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->Id = zx_clone_attr(c, x->Id);

  for (enn = 0, e = &x->EncryptionProperty->gg;
       e && e->g.tok == zx_xenc_EncryptionProperty_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_EncryptionProperty(c,(struct zx_xenc_EncryptionProperty_s*)e,dup_strs);
  	  if (!enn)
  	      x->EncryptionProperty = (struct zx_xenc_EncryptionProperty_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xenc_EncryptionProperties) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_EncryptionProperties(struct zx_ctx* c, struct zx_xenc_EncryptionProperties_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->EncryptionProperty->gg;
       e && e->g.tok == zx_xenc_EncryptionProperty_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_EncryptionProperty(c, (struct zx_xenc_EncryptionProperty_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_EncryptionProperties) */

int zx_WALK_WO_xenc_EncryptionProperties(struct zx_ctx* c, struct zx_xenc_EncryptionProperties_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_EncryptionProperty
#define EL_STRUCT zx_xenc_EncryptionProperty_s
#define EL_NS     xenc
#define EL_TAG    EncryptionProperty

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_EncryptionProperty) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_EncryptionProperty(struct zx_ctx* c, struct zx_xenc_EncryptionProperty_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->Id);
  zx_dup_attr(c, x->Target);


}

/* FUNC(zx_DEEP_CLONE_xenc_EncryptionProperty) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_EncryptionProperty_s* zx_DEEP_CLONE_xenc_EncryptionProperty(struct zx_ctx* c, struct zx_xenc_EncryptionProperty_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_EncryptionProperty_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_EncryptionProperty_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->Id = zx_clone_attr(c, x->Id);
  x->Target = zx_clone_attr(c, x->Target);


  return x;
}

/* FUNC(zx_WALK_SO_xenc_EncryptionProperty) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_EncryptionProperty(struct zx_ctx* c, struct zx_xenc_EncryptionProperty_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;


  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_EncryptionProperty) */

int zx_WALK_WO_xenc_EncryptionProperty(struct zx_ctx* c, struct zx_xenc_EncryptionProperty_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_KeyReference
#define EL_STRUCT zx_xenc_KeyReference_s
#define EL_NS     xenc
#define EL_TAG    KeyReference

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_KeyReference) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_KeyReference(struct zx_ctx* c, struct zx_xenc_KeyReference_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->URI);


}

/* FUNC(zx_DEEP_CLONE_xenc_KeyReference) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_KeyReference_s* zx_DEEP_CLONE_xenc_KeyReference(struct zx_ctx* c, struct zx_xenc_KeyReference_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_KeyReference_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_KeyReference_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->URI = zx_clone_attr(c, x->URI);


  return x;
}

/* FUNC(zx_WALK_SO_xenc_KeyReference) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_KeyReference(struct zx_ctx* c, struct zx_xenc_KeyReference_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;


  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_KeyReference) */

int zx_WALK_WO_xenc_KeyReference(struct zx_ctx* c, struct zx_xenc_KeyReference_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_OriginatorKeyInfo
#define EL_STRUCT zx_xenc_OriginatorKeyInfo_s
#define EL_NS     xenc
#define EL_TAG    OriginatorKeyInfo

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_OriginatorKeyInfo) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_OriginatorKeyInfo(struct zx_ctx* c, struct zx_xenc_OriginatorKeyInfo_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->Id);

  zx_dup_strs_simple_elems(c, x->KeyName);
  for (se = &x->KeyValue->gg;
       se && se->g.tok == zx_ds_KeyValue_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_KeyValue(c, (struct zx_ds_KeyValue_s*)se);
  for (se = &x->RetrievalMethod->gg;
       se && se->g.tok == zx_ds_RetrievalMethod_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_RetrievalMethod(c, (struct zx_ds_RetrievalMethod_s*)se);
  for (se = &x->X509Data->gg;
       se && se->g.tok == zx_ds_X509Data_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_X509Data(c, (struct zx_ds_X509Data_s*)se);
  for (se = &x->PGPData->gg;
       se && se->g.tok == zx_ds_PGPData_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_PGPData(c, (struct zx_ds_PGPData_s*)se);
  for (se = &x->SPKIData->gg;
       se && se->g.tok == zx_ds_SPKIData_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_SPKIData(c, (struct zx_ds_SPKIData_s*)se);
  zx_dup_strs_simple_elems(c, x->MgmtData);
  for (se = &x->EncryptedKey->gg;
       se && se->g.tok == zx_xenc_EncryptedKey_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_EncryptedKey(c, (struct zx_xenc_EncryptedKey_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xenc_OriginatorKeyInfo) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_OriginatorKeyInfo_s* zx_DEEP_CLONE_xenc_OriginatorKeyInfo(struct zx_ctx* c, struct zx_xenc_OriginatorKeyInfo_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_OriginatorKeyInfo_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_OriginatorKeyInfo_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->Id = zx_clone_attr(c, x->Id);

  x->KeyName = zx_deep_clone_simple_elems(c,x->KeyName, dup_strs);
  for (enn = 0, e = &x->KeyValue->gg;
       e && e->g.tok == zx_ds_KeyValue_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_KeyValue(c,(struct zx_ds_KeyValue_s*)e,dup_strs);
  	  if (!enn)
  	      x->KeyValue = (struct zx_ds_KeyValue_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->RetrievalMethod->gg;
       e && e->g.tok == zx_ds_RetrievalMethod_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_RetrievalMethod(c,(struct zx_ds_RetrievalMethod_s*)e,dup_strs);
  	  if (!enn)
  	      x->RetrievalMethod = (struct zx_ds_RetrievalMethod_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->X509Data->gg;
       e && e->g.tok == zx_ds_X509Data_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_X509Data(c,(struct zx_ds_X509Data_s*)e,dup_strs);
  	  if (!enn)
  	      x->X509Data = (struct zx_ds_X509Data_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->PGPData->gg;
       e && e->g.tok == zx_ds_PGPData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_PGPData(c,(struct zx_ds_PGPData_s*)e,dup_strs);
  	  if (!enn)
  	      x->PGPData = (struct zx_ds_PGPData_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->SPKIData->gg;
       e && e->g.tok == zx_ds_SPKIData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_SPKIData(c,(struct zx_ds_SPKIData_s*)e,dup_strs);
  	  if (!enn)
  	      x->SPKIData = (struct zx_ds_SPKIData_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  x->MgmtData = zx_deep_clone_simple_elems(c,x->MgmtData, dup_strs);
  for (enn = 0, e = &x->EncryptedKey->gg;
       e && e->g.tok == zx_xenc_EncryptedKey_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_EncryptedKey(c,(struct zx_xenc_EncryptedKey_s*)e,dup_strs);
  	  if (!enn)
  	      x->EncryptedKey = (struct zx_xenc_EncryptedKey_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xenc_OriginatorKeyInfo) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_OriginatorKeyInfo(struct zx_ctx* c, struct zx_xenc_OriginatorKeyInfo_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  ret = zx_walk_so_simple_elems(c, x->KeyName, ctx, callback);
  if (ret)
    return ret;
  for (e = &x->KeyValue->gg;
       e && e->g.tok == zx_ds_KeyValue_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_KeyValue(c, (struct zx_ds_KeyValue_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->RetrievalMethod->gg;
       e && e->g.tok == zx_ds_RetrievalMethod_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_RetrievalMethod(c, (struct zx_ds_RetrievalMethod_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->X509Data->gg;
       e && e->g.tok == zx_ds_X509Data_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_X509Data(c, (struct zx_ds_X509Data_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->PGPData->gg;
       e && e->g.tok == zx_ds_PGPData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_PGPData(c, (struct zx_ds_PGPData_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->SPKIData->gg;
       e && e->g.tok == zx_ds_SPKIData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_SPKIData(c, (struct zx_ds_SPKIData_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  ret = zx_walk_so_simple_elems(c, x->MgmtData, ctx, callback);
  if (ret)
    return ret;
  for (e = &x->EncryptedKey->gg;
       e && e->g.tok == zx_xenc_EncryptedKey_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_EncryptedKey(c, (struct zx_xenc_EncryptedKey_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_OriginatorKeyInfo) */

int zx_WALK_WO_xenc_OriginatorKeyInfo(struct zx_ctx* c, struct zx_xenc_OriginatorKeyInfo_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_RecipientKeyInfo
#define EL_STRUCT zx_xenc_RecipientKeyInfo_s
#define EL_NS     xenc
#define EL_TAG    RecipientKeyInfo

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_RecipientKeyInfo) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_RecipientKeyInfo(struct zx_ctx* c, struct zx_xenc_RecipientKeyInfo_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->Id);

  zx_dup_strs_simple_elems(c, x->KeyName);
  for (se = &x->KeyValue->gg;
       se && se->g.tok == zx_ds_KeyValue_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_KeyValue(c, (struct zx_ds_KeyValue_s*)se);
  for (se = &x->RetrievalMethod->gg;
       se && se->g.tok == zx_ds_RetrievalMethod_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_RetrievalMethod(c, (struct zx_ds_RetrievalMethod_s*)se);
  for (se = &x->X509Data->gg;
       se && se->g.tok == zx_ds_X509Data_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_X509Data(c, (struct zx_ds_X509Data_s*)se);
  for (se = &x->PGPData->gg;
       se && se->g.tok == zx_ds_PGPData_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_PGPData(c, (struct zx_ds_PGPData_s*)se);
  for (se = &x->SPKIData->gg;
       se && se->g.tok == zx_ds_SPKIData_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_SPKIData(c, (struct zx_ds_SPKIData_s*)se);
  zx_dup_strs_simple_elems(c, x->MgmtData);
  for (se = &x->EncryptedKey->gg;
       se && se->g.tok == zx_xenc_EncryptedKey_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_EncryptedKey(c, (struct zx_xenc_EncryptedKey_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xenc_RecipientKeyInfo) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_RecipientKeyInfo_s* zx_DEEP_CLONE_xenc_RecipientKeyInfo(struct zx_ctx* c, struct zx_xenc_RecipientKeyInfo_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_RecipientKeyInfo_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_RecipientKeyInfo_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->Id = zx_clone_attr(c, x->Id);

  x->KeyName = zx_deep_clone_simple_elems(c,x->KeyName, dup_strs);
  for (enn = 0, e = &x->KeyValue->gg;
       e && e->g.tok == zx_ds_KeyValue_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_KeyValue(c,(struct zx_ds_KeyValue_s*)e,dup_strs);
  	  if (!enn)
  	      x->KeyValue = (struct zx_ds_KeyValue_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->RetrievalMethod->gg;
       e && e->g.tok == zx_ds_RetrievalMethod_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_RetrievalMethod(c,(struct zx_ds_RetrievalMethod_s*)e,dup_strs);
  	  if (!enn)
  	      x->RetrievalMethod = (struct zx_ds_RetrievalMethod_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->X509Data->gg;
       e && e->g.tok == zx_ds_X509Data_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_X509Data(c,(struct zx_ds_X509Data_s*)e,dup_strs);
  	  if (!enn)
  	      x->X509Data = (struct zx_ds_X509Data_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->PGPData->gg;
       e && e->g.tok == zx_ds_PGPData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_PGPData(c,(struct zx_ds_PGPData_s*)e,dup_strs);
  	  if (!enn)
  	      x->PGPData = (struct zx_ds_PGPData_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->SPKIData->gg;
       e && e->g.tok == zx_ds_SPKIData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_SPKIData(c,(struct zx_ds_SPKIData_s*)e,dup_strs);
  	  if (!enn)
  	      x->SPKIData = (struct zx_ds_SPKIData_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  x->MgmtData = zx_deep_clone_simple_elems(c,x->MgmtData, dup_strs);
  for (enn = 0, e = &x->EncryptedKey->gg;
       e && e->g.tok == zx_xenc_EncryptedKey_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_EncryptedKey(c,(struct zx_xenc_EncryptedKey_s*)e,dup_strs);
  	  if (!enn)
  	      x->EncryptedKey = (struct zx_xenc_EncryptedKey_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xenc_RecipientKeyInfo) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_RecipientKeyInfo(struct zx_ctx* c, struct zx_xenc_RecipientKeyInfo_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  ret = zx_walk_so_simple_elems(c, x->KeyName, ctx, callback);
  if (ret)
    return ret;
  for (e = &x->KeyValue->gg;
       e && e->g.tok == zx_ds_KeyValue_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_KeyValue(c, (struct zx_ds_KeyValue_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->RetrievalMethod->gg;
       e && e->g.tok == zx_ds_RetrievalMethod_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_RetrievalMethod(c, (struct zx_ds_RetrievalMethod_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->X509Data->gg;
       e && e->g.tok == zx_ds_X509Data_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_X509Data(c, (struct zx_ds_X509Data_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->PGPData->gg;
       e && e->g.tok == zx_ds_PGPData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_PGPData(c, (struct zx_ds_PGPData_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->SPKIData->gg;
       e && e->g.tok == zx_ds_SPKIData_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_SPKIData(c, (struct zx_ds_SPKIData_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  ret = zx_walk_so_simple_elems(c, x->MgmtData, ctx, callback);
  if (ret)
    return ret;
  for (e = &x->EncryptedKey->gg;
       e && e->g.tok == zx_xenc_EncryptedKey_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_EncryptedKey(c, (struct zx_xenc_EncryptedKey_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_RecipientKeyInfo) */

int zx_WALK_WO_xenc_RecipientKeyInfo(struct zx_ctx* c, struct zx_xenc_RecipientKeyInfo_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_ReferenceList
#define EL_STRUCT zx_xenc_ReferenceList_s
#define EL_NS     xenc
#define EL_TAG    ReferenceList

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_ReferenceList) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_ReferenceList(struct zx_ctx* c, struct zx_xenc_ReferenceList_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */


  for (se = &x->DataReference->gg;
       se && se->g.tok == zx_xenc_DataReference_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_DataReference(c, (struct zx_xenc_DataReference_s*)se);
  for (se = &x->KeyReference->gg;
       se && se->g.tok == zx_xenc_KeyReference_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xenc_KeyReference(c, (struct zx_xenc_KeyReference_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xenc_ReferenceList) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_ReferenceList_s* zx_DEEP_CLONE_xenc_ReferenceList(struct zx_ctx* c, struct zx_xenc_ReferenceList_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_ReferenceList_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_ReferenceList_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */


  for (enn = 0, e = &x->DataReference->gg;
       e && e->g.tok == zx_xenc_DataReference_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_DataReference(c,(struct zx_xenc_DataReference_s*)e,dup_strs);
  	  if (!enn)
  	      x->DataReference = (struct zx_xenc_DataReference_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->KeyReference->gg;
       e && e->g.tok == zx_xenc_KeyReference_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xenc_KeyReference(c,(struct zx_xenc_KeyReference_s*)e,dup_strs);
  	  if (!enn)
  	      x->KeyReference = (struct zx_xenc_KeyReference_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xenc_ReferenceList) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_ReferenceList(struct zx_ctx* c, struct zx_xenc_ReferenceList_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->DataReference->gg;
       e && e->g.tok == zx_xenc_DataReference_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_DataReference(c, (struct zx_xenc_DataReference_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->KeyReference->gg;
       e && e->g.tok == zx_xenc_KeyReference_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xenc_KeyReference(c, (struct zx_xenc_KeyReference_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_ReferenceList) */

int zx_WALK_WO_xenc_ReferenceList(struct zx_ctx* c, struct zx_xenc_ReferenceList_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xenc_Transforms
#define EL_STRUCT zx_xenc_Transforms_s
#define EL_NS     xenc
#define EL_TAG    Transforms

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xenc_Transforms) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xenc_Transforms(struct zx_ctx* c, struct zx_xenc_Transforms_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */


  for (se = &x->Transform->gg;
       se && se->g.tok == zx_ds_Transform_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_Transform(c, (struct zx_ds_Transform_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xenc_Transforms) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xenc_Transforms_s* zx_DEEP_CLONE_xenc_Transforms(struct zx_ctx* c, struct zx_xenc_Transforms_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xenc_Transforms_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xenc_Transforms_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */


  for (enn = 0, e = &x->Transform->gg;
       e && e->g.tok == zx_ds_Transform_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_Transform(c,(struct zx_ds_Transform_s*)e,dup_strs);
  	  if (!enn)
  	      x->Transform = (struct zx_ds_Transform_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xenc_Transforms) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xenc_Transforms(struct zx_ctx* c, struct zx_xenc_Transforms_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Transform->gg;
       e && e->g.tok == zx_ds_Transform_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_Transform(c, (struct zx_ds_Transform_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xenc_Transforms) */

int zx_WALK_WO_xenc_Transforms(struct zx_ctx* c, struct zx_xenc_Transforms_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif


/* EOF -- c/zx-xenc-aux.c */
