/* c/zx-xml-data.h - WARNING: This header was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
/* Datastructure design, topography, and layout
 * Copyright (c) 2006,2010 Sampo Kellomaki (sampo@iki.fi),
 * All Rights Reserved. NO WARRANTY. See file COPYING for
 * terms and conditions of use. Element and attributes names as well
 * as some topography are derived from schema descriptions that were used as
 * input and may be subject to their own copright. */

#ifndef _c_zx_xml_data_h
#define _c_zx_xml_data_h

#include "zx.h"
#include "c/zx-const.h"
#include "c/zx-data.h"

#ifndef ZX_ELEM_EXT
#define ZX_ELEM_EXT  /* This extension point should be defined by who includes this file. */
#endif

#define zx_xml_N_ELEMS 0
#if !defined(zx_xml__ELEM_MAX) && zx_xml_N_ELEMS == 0
#define zx_xml__ELEM_MAX 0
#endif
extern struct zx_el_tok zx_xml_el_tab[zx_xml__ELEM_MAX];
struct zx_el_tok* zx_xml_elem2tok(const char* name, unsigned int name_len);

/* -------------------------- xml_DummyToPullLang -------------------------- */
/* refby( ) */
#ifndef zx_xml_DummyToPullLang_EXT
#define zx_xml_DummyToPullLang_EXT
#endif

struct zx_xml_DummyToPullLang_s {
  ZX_ELEM_EXT
  zx_xml_DummyToPullLang_EXT
  struct zx_attr_s* lang;	/* {0,1} attribute xs:string */
};

struct zx_xml_DummyToPullLang_s* zx_DEC_xml_DummyToPullLang(struct zx_ctx* c, struct zx_xml_DummyToPullLang_s* x);
struct zx_xml_DummyToPullLang_s* zx_NEW_xml_DummyToPullLang(struct zx_ctx* c, struct zx_elem_s* father);
int zx_LEN_SO_xml_DummyToPullLang(struct zx_ctx* c, struct zx_xml_DummyToPullLang_s* x);
char* zx_ENC_SO_xml_DummyToPullLang(struct zx_ctx* c, struct zx_xml_DummyToPullLang_s* x, char* p);
struct zx_str* zx_EASY_ENC_SO_xml_DummyToPullLang(struct zx_ctx* c, struct zx_xml_DummyToPullLang_s* x);

#ifdef ZX_ENA_AUX
struct zx_xml_DummyToPullLang_s* zx_DEEP_CLONE_xml_DummyToPullLang(struct zx_ctx* c, struct zx_xml_DummyToPullLang_s* x, int dup_strs);
void zx_DUP_STRS_xml_DummyToPullLang(struct zx_ctx* c, struct zx_xml_DummyToPullLang_s* x);
int zx_WALK_SO_xml_DummyToPullLang(struct zx_ctx* c, struct zx_xml_DummyToPullLang_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx));
int zx_WALK_WO_xml_DummyToPullLang(struct zx_ctx* c, struct zx_xml_DummyToPullLang_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx));
#endif

#ifdef ZX_ENA_GETPUT
struct zx_attr_s* zx_xml_DummyToPullLang_GET_lang(struct zx_xml_DummyToPullLang_s* x);





void zx_xml_DummyToPullLang_PUT_lang(struct zx_xml_DummyToPullLang_s* x, struct zx_attr_s* y);





#endif

#endif
