/* c/zx-xaspcd1-aux.c - WARNING: This file was auto generated by xsd2sg.pl. DO NOT EDIT!
 * $Id$ */
/* Code generation design Copyright (c) 2006 Sampo Kellomaki (sampo@iki.fi),
 * All Rights Reserved. NO WARRANTY. See file COPYING for terms and conditions
 * of use. Some aspects of code generation were driven by schema
 * descriptions that were used as input and may be subject to their own copyright.
 * Code generation uses a template, whose copyright statement follows. */

/** aux-templ.c  -  Auxiliary functions template: cloning, freeing, walking data
 ** Copyright (c) 2010 Sampo Kellomaki (sampo@iki.fi), All Rights Reserved.
 ** Copyright (c) 2006 Symlabs (symlabs@symlabs.com), All Rights Reserved.
 ** Author: Sampo Kellomaki (sampo@iki.fi)
 ** This is confidential unpublished proprietary source code of the author.
 ** NO WARRANTY, not even implied warranties. Contains trade secrets.
 ** Distribution prohibited unless authorized in writing.
 ** Licensed under Apache License 2.0, see file COPYING.
 ** Id: aux-templ.c,v 1.12 2008-10-04 23:42:14 sampo Exp $
 **
 ** 30.5.2006, created, Sampo Kellomaki (sampo@iki.fi)
 ** 6.8.2006, factored from enc-templ.c to separate file --Sampo
 **
 ** N.B: wo=wire order (needed for exc-c14n), so=schema order
 **/

#include <memory.h>
#include "errmac.h"
#include "zx.h"
#include "c/zx-const.h"
#include "c/zx-data.h"
#include "c/zx-xaspcd1-data.h"



#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xaspcd1_XACMLAuthzDecisionQuery
#define EL_STRUCT zx_xaspcd1_XACMLAuthzDecisionQuery_s
#define EL_NS     xaspcd1
#define EL_TAG    XACMLAuthzDecisionQuery

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xaspcd1_XACMLAuthzDecisionQuery) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xaspcd1_XACMLAuthzDecisionQuery(struct zx_ctx* c, struct zx_xaspcd1_XACMLAuthzDecisionQuery_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->CombinePolicies);
  zx_dup_attr(c, x->Consent);
  zx_dup_attr(c, x->Destination);
  zx_dup_attr(c, x->ID);
  zx_dup_attr(c, x->InputContextOnly);
  zx_dup_attr(c, x->IssueInstant);
  zx_dup_attr(c, x->ReturnContext);
  zx_dup_attr(c, x->Version);

  for (se = &x->Issuer->gg;
       se && se->g.tok == zx_sa_Issuer_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_sa_Issuer(c, (struct zx_sa_Issuer_s*)se);
  for (se = &x->Signature->gg;
       se && se->g.tok == zx_ds_Signature_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_Signature(c, (struct zx_ds_Signature_s*)se);
  for (se = &x->Extensions->gg;
       se && se->g.tok == zx_sp_Extensions_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_sp_Extensions(c, (struct zx_sp_Extensions_s*)se);
  for (se = &x->Request->gg;
       se && se->g.tok == zx_xac_Request_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xac_Request(c, (struct zx_xac_Request_s*)se);
  for (se = &x->Policy->gg;
       se && se->g.tok == zx_xa_Policy_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xa_Policy(c, (struct zx_xa_Policy_s*)se);
  for (se = &x->PolicySet->gg;
       se && se->g.tok == zx_xa_PolicySet_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xa_PolicySet(c, (struct zx_xa_PolicySet_s*)se);
  for (se = &x->ReferencedPolicies->gg;
       se && se->g.tok == zx_xasacd1_ReferencedPolicies_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xasacd1_ReferencedPolicies(c, (struct zx_xasacd1_ReferencedPolicies_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xaspcd1_XACMLAuthzDecisionQuery) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xaspcd1_XACMLAuthzDecisionQuery_s* zx_DEEP_CLONE_xaspcd1_XACMLAuthzDecisionQuery(struct zx_ctx* c, struct zx_xaspcd1_XACMLAuthzDecisionQuery_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xaspcd1_XACMLAuthzDecisionQuery_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xaspcd1_XACMLAuthzDecisionQuery_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->CombinePolicies = zx_clone_attr(c, x->CombinePolicies);
  x->Consent = zx_clone_attr(c, x->Consent);
  x->Destination = zx_clone_attr(c, x->Destination);
  x->ID = zx_clone_attr(c, x->ID);
  x->InputContextOnly = zx_clone_attr(c, x->InputContextOnly);
  x->IssueInstant = zx_clone_attr(c, x->IssueInstant);
  x->ReturnContext = zx_clone_attr(c, x->ReturnContext);
  x->Version = zx_clone_attr(c, x->Version);

  for (enn = 0, e = &x->Issuer->gg;
       e && e->g.tok == zx_sa_Issuer_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_sa_Issuer(c,(struct zx_sa_Issuer_s*)e,dup_strs);
  	  if (!enn)
  	      x->Issuer = (struct zx_sa_Issuer_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Signature->gg;
       e && e->g.tok == zx_ds_Signature_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_Signature(c,(struct zx_ds_Signature_s*)e,dup_strs);
  	  if (!enn)
  	      x->Signature = (struct zx_ds_Signature_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Extensions->gg;
       e && e->g.tok == zx_sp_Extensions_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_sp_Extensions(c,(struct zx_sp_Extensions_s*)e,dup_strs);
  	  if (!enn)
  	      x->Extensions = (struct zx_sp_Extensions_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Request->gg;
       e && e->g.tok == zx_xac_Request_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xac_Request(c,(struct zx_xac_Request_s*)e,dup_strs);
  	  if (!enn)
  	      x->Request = (struct zx_xac_Request_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Policy->gg;
       e && e->g.tok == zx_xa_Policy_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xa_Policy(c,(struct zx_xa_Policy_s*)e,dup_strs);
  	  if (!enn)
  	      x->Policy = (struct zx_xa_Policy_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->PolicySet->gg;
       e && e->g.tok == zx_xa_PolicySet_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xa_PolicySet(c,(struct zx_xa_PolicySet_s*)e,dup_strs);
  	  if (!enn)
  	      x->PolicySet = (struct zx_xa_PolicySet_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->ReferencedPolicies->gg;
       e && e->g.tok == zx_xasacd1_ReferencedPolicies_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xasacd1_ReferencedPolicies(c,(struct zx_xasacd1_ReferencedPolicies_s*)e,dup_strs);
  	  if (!enn)
  	      x->ReferencedPolicies = (struct zx_xasacd1_ReferencedPolicies_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xaspcd1_XACMLAuthzDecisionQuery) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xaspcd1_XACMLAuthzDecisionQuery(struct zx_ctx* c, struct zx_xaspcd1_XACMLAuthzDecisionQuery_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Issuer->gg;
       e && e->g.tok == zx_sa_Issuer_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_sa_Issuer(c, (struct zx_sa_Issuer_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Signature->gg;
       e && e->g.tok == zx_ds_Signature_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_Signature(c, (struct zx_ds_Signature_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Extensions->gg;
       e && e->g.tok == zx_sp_Extensions_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_sp_Extensions(c, (struct zx_sp_Extensions_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Request->gg;
       e && e->g.tok == zx_xac_Request_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xac_Request(c, (struct zx_xac_Request_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Policy->gg;
       e && e->g.tok == zx_xa_Policy_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xa_Policy(c, (struct zx_xa_Policy_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->PolicySet->gg;
       e && e->g.tok == zx_xa_PolicySet_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xa_PolicySet(c, (struct zx_xa_PolicySet_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->ReferencedPolicies->gg;
       e && e->g.tok == zx_xasacd1_ReferencedPolicies_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xasacd1_ReferencedPolicies(c, (struct zx_xasacd1_ReferencedPolicies_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xaspcd1_XACMLAuthzDecisionQuery) */

int zx_WALK_WO_xaspcd1_XACMLAuthzDecisionQuery(struct zx_ctx* c, struct zx_xaspcd1_XACMLAuthzDecisionQuery_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif




#ifdef EL_NAME
#undef EL_NAME
#endif
#ifdef EL_STRUCT
#undef EL_STRUCT
#endif
#ifdef EL_NS
#undef EL_NS
#endif
#ifdef EL_TAG
#undef EL_TAG
#endif

#define EL_NAME   xaspcd1_XACMLPolicyQuery
#define EL_STRUCT zx_xaspcd1_XACMLPolicyQuery_s
#define EL_NS     xaspcd1
#define EL_TAG    XACMLPolicyQuery

#ifdef ZX_ENA_AUX

/* FUNC(zx_DUP_STRS_xaspcd1_XACMLPolicyQuery) */

/* Depth first traversal of data structure to copy its simple strings
 * to memory allocated from the memory allocator. The decoder will
 * use the underlying wireprotocol PDU buffer for strings, i.e.
 * strings are not copied - they point to the real data. If the
 * datastructure needs to outlast the protocol data or needs a different
 * memory allocation strategy, you need to call this function.  */

/* Called by: */
void zx_DUP_STRS_xaspcd1_XACMLPolicyQuery(struct zx_ctx* c, struct zx_xaspcd1_XACMLPolicyQuery_s* x)
{
  struct zx_elem_s* se  MAYBE_UNUSED;
  zx_dup_strs_common(c, &x->gg);
  /* *** deal with xmlns specifications in exc c14n way */

  zx_dup_attr(c, x->Consent);
  zx_dup_attr(c, x->Destination);
  zx_dup_attr(c, x->ID);
  zx_dup_attr(c, x->IssueInstant);
  zx_dup_attr(c, x->Version);

  for (se = &x->Issuer->gg;
       se && se->g.tok == zx_sa_Issuer_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_sa_Issuer(c, (struct zx_sa_Issuer_s*)se);
  for (se = &x->Signature->gg;
       se && se->g.tok == zx_ds_Signature_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_ds_Signature(c, (struct zx_ds_Signature_s*)se);
  for (se = &x->Extensions->gg;
       se && se->g.tok == zx_sp_Extensions_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_sp_Extensions(c, (struct zx_sp_Extensions_s*)se);
  for (se = &x->Request->gg;
       se && se->g.tok == zx_xac_Request_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xac_Request(c, (struct zx_xac_Request_s*)se);
  for (se = &x->Target->gg;
       se && se->g.tok == zx_xa_Target_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xa_Target(c, (struct zx_xa_Target_s*)se);
  for (se = &x->PolicySetIdReference->gg;
       se && se->g.tok == zx_xa_PolicySetIdReference_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xa_PolicySetIdReference(c, (struct zx_xa_PolicySetIdReference_s*)se);
  for (se = &x->PolicyIdReference->gg;
       se && se->g.tok == zx_xa_PolicyIdReference_ELEM;
       se = (struct zx_elem_s*)se->g.n)
    zx_DUP_STRS_xa_PolicyIdReference(c, (struct zx_xa_PolicyIdReference_s*)se);

}

/* FUNC(zx_DEEP_CLONE_xaspcd1_XACMLPolicyQuery) */

/* Depth first traversal of data structure to clone it and its sublements.
 * The simple strings are handled as a special case according to dup_strs flag. */

/* Called by: */
struct zx_xaspcd1_XACMLPolicyQuery_s* zx_DEEP_CLONE_xaspcd1_XACMLPolicyQuery(struct zx_ctx* c, struct zx_xaspcd1_XACMLPolicyQuery_s* x, int dup_strs)
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  struct zx_elem_s* en  MAYBE_UNUSED;
  struct zx_elem_s* enn MAYBE_UNUSED;

  x = (struct zx_xaspcd1_XACMLPolicyQuery_s*)zx_clone_elem_common(c, &x->gg, sizeof(struct zx_xaspcd1_XACMLPolicyQuery_s), dup_strs);
  /* *** deal with xmlns specifications in exc c14n way */

  x->Consent = zx_clone_attr(c, x->Consent);
  x->Destination = zx_clone_attr(c, x->Destination);
  x->ID = zx_clone_attr(c, x->ID);
  x->IssueInstant = zx_clone_attr(c, x->IssueInstant);
  x->Version = zx_clone_attr(c, x->Version);

  for (enn = 0, e = &x->Issuer->gg;
       e && e->g.tok == zx_sa_Issuer_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_sa_Issuer(c,(struct zx_sa_Issuer_s*)e,dup_strs);
  	  if (!enn)
  	      x->Issuer = (struct zx_sa_Issuer_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Signature->gg;
       e && e->g.tok == zx_ds_Signature_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_ds_Signature(c,(struct zx_ds_Signature_s*)e,dup_strs);
  	  if (!enn)
  	      x->Signature = (struct zx_ds_Signature_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Extensions->gg;
       e && e->g.tok == zx_sp_Extensions_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_sp_Extensions(c,(struct zx_sp_Extensions_s*)e,dup_strs);
  	  if (!enn)
  	      x->Extensions = (struct zx_sp_Extensions_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Request->gg;
       e && e->g.tok == zx_xac_Request_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xac_Request(c,(struct zx_xac_Request_s*)e,dup_strs);
  	  if (!enn)
  	      x->Request = (struct zx_xac_Request_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->Target->gg;
       e && e->g.tok == zx_xa_Target_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xa_Target(c,(struct zx_xa_Target_s*)e,dup_strs);
  	  if (!enn)
  	      x->Target = (struct zx_xa_Target_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->PolicySetIdReference->gg;
       e && e->g.tok == zx_xa_PolicySetIdReference_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xa_PolicySetIdReference(c,(struct zx_xa_PolicySetIdReference_s*)e,dup_strs);
  	  if (!enn)
  	      x->PolicySetIdReference = (struct zx_xa_PolicySetIdReference_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }
  for (enn = 0, e = &x->PolicyIdReference->gg;
       e && e->g.tok == zx_xa_PolicyIdReference_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
  	  en=(struct zx_elem_s*)zx_DEEP_CLONE_xa_PolicyIdReference(c,(struct zx_xa_PolicyIdReference_s*)e,dup_strs);
  	  if (!enn)
  	      x->PolicyIdReference = (struct zx_xa_PolicyIdReference_s*)en;
  	  else
  	      enn->g.n = &en->g;
  	  enn = en;
  }

  return x;
}

/* FUNC(zx_WALK_SO_xaspcd1_XACMLPolicyQuery) */

/* Depth first traversal of the tree in either schema order or the wire order. */
 
int zx_WALK_SO_xaspcd1_XACMLPolicyQuery(struct zx_ctx* c, struct zx_xaspcd1_XACMLPolicyQuery_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  struct zx_elem_s* e   MAYBE_UNUSED;
  int ret = callback(&x->gg.g, ctx);
  if (ret)
    return ret;
  
  /* *** deal with xmlns specifications in exc c14n way */


  
  ret = zx_walk_so_unknown_attributes(c, &x->gg, ctx, callback); 
  if (ret)
    return ret;

  for (e = &x->Issuer->gg;
       e && e->g.tok == zx_sa_Issuer_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_sa_Issuer(c, (struct zx_sa_Issuer_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Signature->gg;
       e && e->g.tok == zx_ds_Signature_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_ds_Signature(c, (struct zx_ds_Signature_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Extensions->gg;
       e && e->g.tok == zx_sp_Extensions_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_sp_Extensions(c, (struct zx_sp_Extensions_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Request->gg;
       e && e->g.tok == zx_xac_Request_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xac_Request(c, (struct zx_xac_Request_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->Target->gg;
       e && e->g.tok == zx_xa_Target_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xa_Target(c, (struct zx_xa_Target_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->PolicySetIdReference->gg;
       e && e->g.tok == zx_xa_PolicySetIdReference_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xa_PolicySetIdReference(c, (struct zx_xa_PolicySetIdReference_s*)e, ctx, callback);
    if (ret)
      return ret;
  }
  for (e = &x->PolicyIdReference->gg;
       e && e->g.tok == zx_xa_PolicyIdReference_ELEM;
       e = (struct zx_elem_s*)e->g.n) {
    ret = zx_WALK_SO_xa_PolicyIdReference(c, (struct zx_xa_PolicyIdReference_s*)e, ctx, callback);
    if (ret)
      return ret;
  }

  
  return zx_walk_so_unknown_elems_and_content(c, &x->gg, ctx, callback);
}

/* FUNC(zx_WALK_WO_xaspcd1_XACMLPolicyQuery) */

int zx_WALK_WO_xaspcd1_XACMLPolicyQuery(struct zx_ctx* c, struct zx_xaspcd1_XACMLPolicyQuery_s* x, void* ctx, int (*callback)(struct zx_node_s* node, void* ctx))
{
  ERR("*** walk_wo not implemented %d", 0);
  return 0;
}

#endif


/* EOF -- c/zx-xaspcd1-aux.c */
